# Generated by Django 5.0.3 on 2024-03-09 12:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='chatbot',
            old_name='output_text',
            new_name='gemini_output',
        ),
        migrations.RenameField(
            model_name='chatbot',
            old_name='input_text',
            new_name='text_input',
        ),
        migrations.RemoveField(
            model_name='chatbot',
            name='timestamp',
        ),
        migrations.AddField(
            model_name='chatbot',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='chatbot',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='GeminiUser', to=settings.AUTH_USER_MODEL),
        ),
    ]
